import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { NextUIProvider } from '@/hooks/next-ui-provider'
import { AuthProvider } from '@/hooks/auth-provider'
import { ThemeProvider } from '@/hooks/theme-provider'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PictoSeq',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={cn(inter.className, 'bg-background')}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            <NextUIProvider>
              {children}
            </NextUIProvider>
          </AuthProvider>
        </ThemeProvider>
      </body >
    </html >
  )
}
